name: Deploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Build
      run: cargo build --release 

    - name: Prepare dist
      run: |
        {
        mkdir dist
        cp scripts/deploy.sh dist
        cp scripts/restart_on_crash.sh dist
        cp -r img dist
        cp target/release/mordoprojekt dist/mordoprojekt-bot
        sed -e "s|DISCORD_BOT_TOKEN|${{ secrets.DISCORD_TOKEN }}|" config-default.toml > dist/config.toml
        }

    - name: Copy dist to VPS
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        source: "dist"
        target: "~/"

    - name: Run bot
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        script: |
          cd dist
          bash ./scripts/deploy.sh
